# Generated by Django 5.0 on 2023-12-28 22:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CertificationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('correct', models.BooleanField()),
                ('ball', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CertificationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('requirements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CertificationAnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certification_answers')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Certification.certificationanswer')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='certification_tasks')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Certification.certificationlevel')),
                ('сategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Certification.category')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Certification.competency')),
            ],
        ),
        migrations.AddField(
            model_name='certificationanswer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Certification.certificationtask'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='Certification.certificationlevel')),
                ('competencies', models.ManyToManyField(blank=True, related_name='teachers', to='Certification.competency')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
                ('сategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='Certification.category')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('answer', models.ManyToManyField(related_name='certification_sessions', to='Certification.certificationanswer')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_sessions', to='Certification.certificationlevel')),
                ('task', models.ManyToManyField(related_name='certification_sessions', to='Certification.certificationtask')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_sessions', to='Certification.competency')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_sessions', to='Certification.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certification_results', to='Certification.certificationsession')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_results', to='Certification.teacher')),
            ],
        ),
    ]
