# Generated by Django 5.0 on 2023-12-28 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificationsession',
            name='passed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='certificationsession',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationanswer',
            name='ball',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationanswer',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationanswer',
            name='correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationlevel',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationtask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certification_tasks'),
        ),
        migrations.AlterField(
            model_name='certificationtask',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Certification.certificationlevel'),
        ),
        migrations.AlterField(
            model_name='certificationtask',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competency',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='certification_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='Certification.certificationlevel'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='competencies',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='Certification.competency'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='сategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='Certification.category'),
        ),
        migrations.DeleteModel(
            name='CertificationResult',
        ),
    ]
