# Generated by Django 5.0 on 2023-12-28 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='certificationanswer',
            name='result',
        ),
        migrations.RemoveField(
            model_name='certificationresult',
            name='task',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.AddField(
            model_name='certificationtask',
            name='сategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Certification.category'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='certification_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='Certification.certificationlevel'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='competencies',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='Certification.competency'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='сategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='Certification.category'),
        ),
        migrations.AlterField(
            model_name='certificationtask',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CertificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('answer', models.ManyToManyField(related_name='certification_sessions', to='Certification.certificationanswer')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_sessions', to='Certification.competency')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_sessions', to='Certification.certificationlevel')),
                ('task', models.ManyToManyField(related_name='certification_sessions', to='Certification.certificationtask')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_sessions', to='Certification.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='certificationresult',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certification_results', to='Certification.certificationsession'),
        ),
    ]
