# Generated by Django 5.0 on 2023-12-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0002_rename_subject_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationtask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certification_tasks'),
        ),
    ]
