# Generated by Django 5.0 on 2023-12-29 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0002_certificationsession_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationsession',
            name='level',
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certification_sessions', to='Certification.certificationlevel'),
        ),
    ]
