# Generated by Django 5.0 on 2023-12-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0003_remove_certificationsession_level_category_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationsession',
            name='answer',
            field=models.ManyToManyField(null=True, related_name='certification_sessions', to='Certification.certificationanswer'),
        ),
        migrations.AlterField(
            model_name='certificationsession',
            name='task',
            field=models.ManyToManyField(null=True, related_name='certification_sessions', to='Certification.certificationtask'),
        ),
    ]
