# Generated by Django 5.0 on 2023-12-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0003_alter_certificationtask_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competency',
            new_name='Competency_o',
        ),
    ]
