# Generated by Django 5.0 on 2023-12-29 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0004_alter_certificationsession_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationsession',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certification_sessions', to='Certification.category'),
        ),
    ]
